myapp/urls.py
from django.conf.urls import patterns, url

from myapp import views


urlpatterns = patterns('',
    url(r'home', views.home,
        name='home',),

    url(r'about', views.aboutus,
        name='aboutus',),

    url(r'terms-of-use', views.termsofuse,
        name='terms-of-use',),

    url(r'faqs', views.faqs,
        name='faqs',),
    url(r'privacy-policy', views.privacypolicy,
        name='privacy-policy',),
    url(r'billing-system', views.billingsystem,
        name='billing-system',),
    url(r'refund-policy', views.refundpolicy,
        name='refund-policy',),

    url(r'ticket-system', views.ticketsystem,
        name='ticket-system',),

    url(r'fabricfilter', views.fabricfilter,
        name='fabricfilter',),

    url(r'location', views.location,
        name='location',),

    url(r'workfilter', views.workfilter,
        name='workfilter',),

    url(r'savedress', views.savedress,
        name='savedress',),

    url(r'item_cart', views.item_cart,
        name='item_cart',),

    url(r'cart_delete', views.cart_delete,
        name='cart_delete',),

    url(r'login', views.login_user,
        name='login_user',),
    url(r'register', views.register_user,
        name='register_user',),
    url(r'shop', views.shop,
        name='shop',),
    url(r'item', views.item,
        name='item',),
    url(r'subscribe', views.subscribe,
        name='subscribe',),

    url(r'search', views.search,
        name='search',),

    url(r'wish_delete', views.wish_delete,
        name='wish_delete',),
    url(r'logout', views.logout_user,
        name='logout_user',),

    url(r'review', views.review,
        name='review',),

    url(r'sizechart_update', views.sizechart_update,
        name='sizechart_update',),

    url(r'createdress', views.createdress,
        name='createdress',),

    url(r'customizedress', views.customizedress,
        name='customizedress',),

    url(r'showproducts', views.showproducts,
        name='showproducts',),

    url(r'addproduct', views.addproduct,
        name='addproduct',),

    url(r'addcategory', views.addcategory,
        name='addcategory',),

    url(r'addsubcategory', views.addsubcategory,
        name='addsubcategory',),

    url(r'admin_deleteproduct', views.deleteproduct,
        name='deleteproduct',),

    url(r'adminupload', views.adminupload,
        name='adminupload',),

    url(r'profile', views.user_profile,
        name='user_profile',),

    url(r'price', views.price,
        name='price',),

    url(r'filter_color', views.filter_color,
        name='filter_color',),

    url(r'filter_occasion', views.filter_occasion,
        name='filter_occasion',),

    url(r'address', views.user_profile_address,
        name='user_profile_address',),

    url(r'pastorders', views.user_profile_pastorders,
        name='user_profile_pastorders',),
    url(r'wishlist', views.user_profile_wishlist,
        name='user_profile_wishlist',),

    url(r'add_wish', views.add_wish,
        name='add_wish',),
    url(r'creditcard', views.user_profile_creditcard,
        name='user_profile_creditcard',),
    url(r'sizechart', views.user_profile_sizechart,
        name='user_profile_sizechart',),
)

myproject/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()
urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'myproject.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^user/',include('myapp.urls')),
)

myapp/models.py
from django.contrib.auth.models import User
from django.db import models

class UserProfile(models.Model):
    #required by the auth model
    user = models.OneToOneField(User, unique=True)
    fullname = models.CharField(max_length=30, null=True, blank=True)
    length_blouse = models.IntegerField(null = True, blank = True)
    waist_blouse = models.IntegerField(null = True, blank = True)
    sleeve_length = models.IntegerField(null = True, blank = True)
    neck_front = models.IntegerField(null = True, blank = True)
    bust = models.IntegerField(null = True, blank = True)
    shoulder = models.IntegerField(null = True, blank = True)
    sleeve_width = models.IntegerField(null = True, blank = True)
    neck_back = models.IntegerField(null = True, blank = True)
    address_line1= models.CharField(max_length=100, null=True, blank=True)
    address_line2= models.CharField(max_length=100, null=True, blank=True)
    city = models.CharField(max_length=50, null=True, blank=True)
    state = models.CharField(max_length=50, null=True, blank=True)
    postcode = models.IntegerField(null=True,blank=True)
    cardname = models.CharField(max_length=100, null=True, blank=True)
    cardno = models.IntegerField(null=True,blank=True)
    exp_month = models.CharField(max_length=50, null=True, blank=True)
    exp_year = models.IntegerField(null=True,blank=True)
    cvv = models.IntegerField(null=True,blank=True)

class Category(models.Model):
	name = models.CharField(max_length = 100)
	description = models.CharField(max_length = 300)
	categoryID = models.IntegerField(primary_key = True)

	def __str__(self):
		return self.name

class SubCategory(models.Model):
	name = models.CharField(max_length = 100,primary_key = True)
	category = models.ForeignKey(Category)
	SubCategoryID = models.IntegerField(null = True, blank = True)


	def __str__(self):              
		return self.name
'''
def get_upload_file_name(instance, filename):
	return "%s_%s" % (str(time()).replace('.','_'),filename)'''

class Product(models.Model):
	#image = models.ImageField(upload_to = 'media/', blank = True, null = True) #, height_field = '', width_field = '')
	image = models.ImageField(upload_to = "home/",null = True)
	name = models.CharField(max_length = 100)
	price = models.IntegerField()
	productID = models.IntegerField(primary_key = True)
	description = models.CharField(max_length = 300,default = "none")
	unitsInOrder = models.IntegerField(default = 0)
	unitsInStock = models.IntegerField(default = 0)
	subcategory = models.ForeignKey(SubCategory, null = True)
	views = models.IntegerField(null = True)

	def __str__(self):             
		return self.productID

class Images(models.Model):
	image = models.ImageField(upload_to = "home/")
	name = models.CharField(max_length = 50)
	product = models.ForeignKey(Product, null = True)

class Review(models.Model):
	user = models.CharField(max_length = 50)
	description = models.CharField(max_length = 300)
	time = models.DateTimeField(auto_now_add = True)
	product = models.ForeignKey(Product)

class Fabric(models.Model):
    fabrics = models.CharField(max_length = 60)
    product = models.ManyToManyField(Product, null = True, blank = True)

class Color(models.Model):
    colors = models.CharField(max_length = 60)
    product = models.ManyToManyField(Product, null = True, blank = True)

class Occasion(models.Model):
    occasions = models.CharField(max_length = 60)
    product = models.ManyToManyField(Product, null = True)

class Work(models.Model):
    works = models.CharField(max_length = 60)
    product = models.ManyToManyField(Product, null = True)

class Cart(models.Model):
    cart_products = models.CharField(max_length = 60,null=True)
    quantity = models.IntegerField(default = 1)
    user = models.ForeignKey(UserProfile, null = True)

class Wishlist(models.Model):
	wish_products = models.IntegerField()
	user = models.ForeignKey(UserProfile,null = True)

class Pastorders(models.Model):
	orderno = models.IntegerField()
	user = models.ForeignKey(UserProfile,null = True)

class Order(models.Model):
	orderID = models.IntegerField(primary_key = True)
	customerID = models.IntegerField()
	orderDate = models.IntegerField()
	shipperID = models.IntegerField()
	billID = models.IntegerField()
	totalprice = models.IntegerField()

	def __str__(self):              
		return self.orderID

class OrderProduct(models.Model):
	productID = models.OneToOneField(Product)
	order = models.ForeignKey(Order)

class Mailinglist(models.Model):
	mail = models.CharField(max_length = 50, null = True)

class Border(models.Model):
	image = models.ImageField(upload_to = "border/")
	borderID = models.IntegerField(primary_key = True)

class Base(models.Model):
	mask_suit = models.ImageField(upload_to = "base/")
	mask_model = models.ImageField(upload_to = "base/")
	mask_sideborder = models.ImageField(upload_to = "base/")
	mask_neckborder = models.ImageField(upload_to = "base/")
	mask_bottomborder = models.ImageField(upload_to = "base/")
	image = models.ImageField(upload_to = "base/")
	baseID = models.IntegerField(primary_key = True)

class Pattern(models.Model):
	image = models.ImageField(upload_to = "pattern/")
	patternID = models.IntegerField(primary_key = True)

class Butta(models.Model):
	image = models.ImageField(upload_to = "butta/")
	buttaID = models.IntegerField(primary_key = True)

templates/addproduct.html
<form action="/user/addproduct/" method="POST" enctype="multipart/form-data">

    {{ state }}
	{% csrf_token %}
                <p>
                    <input id="id_image" type="file" class="" name="image">
                 </p>
                 <p>
                    <input type = "text" name="name" placeholder = "Enter name of Image">

                </p>
                <p>
                    <input type = "text" name="primaryID" placeholder = "Enter ID of Primary Image">

                </p>
                <p>
                    <input type = "text" name="price" placeholder = "Enter price of product">

                </p>
                <p>
                    <input type = "text" name="description" placeholder = "Enter Description of product">

                </p>
                <p>
                    <input type = "text" name="unitsinorder" placeholder = "Enter number of units in order of product">

                </p>
                <p>
                    <input type = "text" name="subcategory" placeholder = "Enter subcategoryID of product">

                </p>
                <p>
                    <input type = "text" name="fabrics" placeholder = "Enter fabrics of product"> Seperate by commas

                </p>
                <p>
                    <input type = "text" name="color" placeholder = "Enter color of product"> Seperate by commas

                </p>
                <p>
                    <input type = "text" name="occasion" placeholder = "Enter occasion of product"> Seperate by commas

                </p>
                <p>
                    <input type = "text" name="work" placeholder = "Enter work of product"> Seperate by commas

                </p>
                <input type="submit" value="Submit" />
</form>

templates/addsubcategory.html
<form action="/user/addsubcategory/" method="POST">

    {{ state }}
	{% csrf_token %}
                
                 <p>
                    <input type = "text" name="name" placeholder = "Enter name of SubCategory">

                </p>
                <p>
                    <input type = "text" name="subcategoryID" placeholder = "Enter ID of SubCategory">

                </p>
              
                <p>
                    <input type = "text" name="categoryID" placeholder = "Enter ID of Category it belongs to.">

                </p>
                <input type="submit" value="Submit" />
</form>

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{% block title %} Home{% endblock %} | NIKScreations</title>
    
    <link href = "{{STATIC_URL}}css/bootstrap.min.css" rel = "stylesheet">
    <link href = "{{STATIC_URL}}css/animate.css" rel = "stylesheet"> 
    <link href = "{{STATIC_URL}}css/font-awesome.min.css" rel = "stylesheet">
    <link href = "{{STATIC_URL}}css/main.css" rel = "stylesheet">
    <link href = "{{STATIC_URL}}css/responsive.css	" rel = "stylesheet">
    <link href = "{{STATIC_URL}}css/side-menu.css" rel = "stylesheet">
    <link href = "{{STATIC_URL}}css/bootstrap-tour.min.css" rel = "stylesheet">
    <script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>
  
    <link rel="shortcut icon" href="images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="images/ico/apple-touch-icon-57-precomposed.png">

    
   	<style>
	h4{
		font-size: 120%;
	}
	</style>
	{%block stylesheets%}{%endblock%}

    

	
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->       

</head><!--/head-->

	<header id="header"><!--header-->
		<div class="header_top" style = "background-color:#1F7964"><!--header_top-->
			<div class="container">
				<div class="row">
					<div class="col-sm-6">
						<div class="contactinfo">
							<ul class="nav nav-pills">
								<li><a href="/user/home/" style = "color:#fff"><b> Home</b></a></li>
								<li><a href="/user/about/" style = "color:#fff"><b> About</b></a></li>
								<li><a href="/user/location/" style = "color:#fff"><b> Store Location</b></a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-6">
						<div class="social-icons pull-right">
							<ul class="nomargin">
								{% if user.is_authenticated %}
    								<li><a href="/user/profile/"><i class="fa fa-lock"></i>My account</a></li>
    								<li><a href="/user/logout/"><i class="fa fa-lock"></i>Logout</a></li>
								{% else %}
    									<li><a href="/user/login/"><i class="fa fa-lock"></i>Login/ Register</a></li>
								{% endif %}
					

							</ul>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header_top-->

		
		<div class="header-middle" style="background-color:white" ><!--header-middle-->
			<div class="container">
				<div class="row" >
					<div class="col-md-7" >
						<div class="logo pull-left">
							
							<a href="/user/home/" style="color:rgb(16,145,115);float:left"><h2 style="font-family:'Open Sans','Open Sans',Arial,sans-serif,sans-serif"><b>NIKS</b></h2></a>
							<a href="/user/home/" style="color:gray;"><h2 style="font-family:'Open Sans','Open Sans',Arial,sans-serif,sans-serif">-Creations</h2></a>
							
							
							<p class="lead" style="font-family:'Open Sans','Open Sans',Arial,sans-serif,sans-serif;color:gray"><small>"Taste the originality and creativity at it's best."</small></p>
						</div>			
					</div>
					<div class="col-md-4 pull-right">
						<div class = "pull-right menuButtons" style="margin-top:15px ">
							<a href="/user/createdress/" class="btn btn-default btn-lg" >Create a Dress</a>
							{% block ShopTogether %}{% endblock %}

						</div><br>
						<div class="search_box pull-right">
							<form action = "/user/search/" method = "POST">
							{% csrf_token %}
							<input type ="hidden" name="page" value = "1" />
							<input type="text" style = "color:rgb(16,145,115)" name = "search" placeholder="Search"/>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div><!--/header-middle-->
		 
		<div class="header-botttom">
			<nav class="navbar navbar-default">
				<div class="container-fluid">
					
					<div class="navbar-header">
						{%block menubutton%}{%endblock%}
						<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
							<span class="sr-only">Toggle navigation</span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						
					</div>

					
					<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav">
					{% for cat in categories %}
						{% if cat.name != "New Arrivals"%}
							<li class="dropdown">

								<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><h4 style="font-family:'Open Sans',Arial,sans-serif">{{ cat.name }}<span class="caret"></span></h4></a>
								<ul class="dropdown-menu" role="menu">
										{% for sub_cat in cat.subcategory_set.all %}
									   		<li><a href="/user/shop?sub={{ sub_cat.name }}">{{ sub_cat.name }}</a></li>
										{% endfor %}
								</ul>
							</li>
							
						{% endif %}
					{% endfor %}
					</ul>
				</div>
			</div>
		</nav>
	</div>

	</header>
	<body>
	{% block body %}{% endblock%}
	</body>
		<footer id="footer"><!--Footer-->
		
		<div class="footer-widget">
			<div class="container">
				<div class = "row">
					<div class = "col-sm-2">
						<div class="single-widget">
							<h2><b>Policies</b></h2>
							<ul class="nav nav-pills nav-stacked">
								<li><a href="/user/terms-of-use">Terms of Use</a></li>
								<li><a href="/user/privacy-policy">Privacy Policy</a></li>
								<li><a href="/user/refund-policy">Refund Policy</a></li>
								<li><a href="/user/billing-system">Billing System</a></li>
								<li><a href="/user/ticket-system">Ticket System</a></li>
								<li><a href="/user/faqs">FAQs</a></li>
							</ul>
						</div>
					</div>
					<div class="col-sm-3 col-sm-offset-1">
						<h3>Subscribe to us</h3>
						{{ state }}
							<form action="/user/subscribe/" class="searchform" method="POST">
							{% csrf_token %}
								<input type="email" name ="subscriber" placeholder="Your email address" />
								<button type="submit" class="btn btn-default"><i class="fa fa-arrow-circle-o-right"></i></button>
								<p>Get the most recent updates from <br />our site and be updated your self...</p>
							</form>
					</div>
				</div>
			</div>
		</div>
	</footer>


    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.scrollUp.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/jquery.prettyPhoto.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/main.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/bootstrap.min.js"></script>
    <script type="text/javascript" src="{{ STATIC_URL }}js/rango-jquery.js"></script>
        <script type="text/javascript" src="{{ STATIC_URL }}js/bootstrap-tour.min.js"></script>
    <script src="https://togetherjs.com/togetherjs-min.js"></script>
 {%block scripts%}{%endblock%}

</html>

templates/billing-system.html
{%extends 'base.html'%}
{%block title%}About Us{%endblock%}

{%block stylesheets%}
<style type="text/css">
		section.about {
    color: #000;
    background: #fff;
}
section.about hr{
	width: 70%;
}
section.about a,
section.about a:hover,
section.about a:focus,
section.about a:active,
section.about a.active {
    outline: 0;
    color: #2c3e50;
}
p{
	font-size: 16px;
}
		</style>
{%endblock%}

{%block ShopTogether%}
	<a href="#" onclick="TogetherJS(this); return false;" class="btn btn-default btn-lg" >Shop Together</a>
{%endblock%}



{%block body%}

		
<section class="about" id="about">
          <div class="container">
            <div class="row" style="text-align:center">
                <div class="col-lg-12">
                    <h1>Billing System</h1>
                    <hr>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec pharetra magna quis mi rutrum tincidunt. Suspendisse eu purus nec diam consectetur pellentesque ut id dui. Vestibulum suscipit hendrerit nibh, eu mattis nisl. In blandit lacus ac maximus ultrices. Suspendisse potenti. Donec id nisi hendrerit, tincidunt felis eget, viverra lacus. Phasellus eu convallis nisi. Nam enim est, posuere sed erat sit amet, dapibus tempor tortor. </p>
                </div>
                <div class="col-lg-8 col-lg-offset-2">
                    <p>Pellentesque ac facilisis metus. Maecenas tempor aliquam dui sed commodo. Sed euismod massa vel ipsum scelerisque iaculis. Pellentesque non suscipit augue, nec rutrum libero. Curabitur facilisis ante eget sem efficitur aliquet at in purus. Vivamus lacinia at est vitae cursus. Praesent laoreet massa vel consequat semper. Nullam at urna varius, viverra urna at, pellentesque metus. Nunc scelerisque hendrerit metus, eget porta arcu interdum sed.</p>
                </div>
    
            </div>
        </div>
    </section>

{%endblock%}

templates/create-dress.html
<!DOCTYPE html>
{% extends 'base.html'%}
{%block title%}Create Dress{%endblock%}
{%block body%}
<div class="col-sm-12 padding-right">
					
					<h2 class="title" align="center"> Select a Base Type</h2>
					<div class="features_items"><!--features_items-->
					
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">
										{% for b in bases %}
										<img src="{{STATIC_URL}}{{ b.image.url }}" alt="" />
								
										<a href="#" class="btn btn-default">Select</a>
										{% endfor %}
									</div>

								</div>
								
							</div>
						</div>
						
					</div><!--features_items-->
				</div>
{%endblock%}

templates/index.html
<!DOCTYPE html>
{% extends 'base.html'%}

{% block ShopTogether %}
	<a href="#" onclick="TogetherJS(this); return false;" class="btn btn-default btn-lg" >Shop Together</a>
{% endblock %}

{%block body%}
	<section id="slider"><!--slider-->
		<div class="container">
			<div class="row">
				<div class="col-sm-12 col-md-12">
					<div id="slider-carousel" class="carousel slide" data-ride="carousel">
						<ol class="carousel-indicators">
							<li data-target="#slider-carousel" data-slide-to="0" class="active"></li>
							<li data-target="#slider-carousel" data-slide-to="1"></li>
							<li data-target="#slider-carousel" data-slide-to="2"></li>
						</ol>
						
						<div class="carousel-inner">
							<div class="item active">
								
								<div class="col-sm-12 col-md-12">
									<img src="{{ STATIC_URL }}images/home/sample3.jpg" class="img-responsive center-block" alt="" />
									<!-- <img src="images/home/pricing.png"  class="pricing" alt="" /> -->
								</div>
							</div>
							<div class="item">
							
								<div class="col-sm-12 col-md-12">
									<img src="{{ STATIC_URL }}images/home/sample4.jpg" class="img-responsive center-block" alt="" />
									
								</div>
							</div>
							
							<div class="item">
							
								<div class="col-sm-12 col-md-12">
									<img src="{{ STATIC_URL }}images/home/sample5.jpg" class="img-responsive center-block" alt="" />
									
								</div>
							</div>
							
						</div>
						
						<a href="#slider-carousel" class="left control-carousel hidden-xs" data-slide="prev">
							<i class="fa fa-angle-left"></i>
						</a>
						<a href="#slider-carousel" class="right control-carousel hidden-xs" data-slide="next">
							<i class="fa fa-angle-right"></i>
						</a>
					</div>
					
				</div>

							<div style="margin-top:80px"class="col-sm-12 recommended_items"><!--recommended_items-->
								<h2 class="title text-center">New Arrivals</h2>

								<div id="recommended-item-carousel" class="carousel slide" data-ride="carousel">
									<div class="carousel-inner">
										
											{% for p in products %}

											{% if forloop.first%}
											<div class="item active">
											{% elif forloop.counter|divisibleby:4%}
											<div class="item">
											{%endif %}

											<div class="col-sm-4">
												<div class="product-image-wrapper">
													<div class="single-products">
														<div class="productinfo text-center">
															<a href = "/user/item/?item={{ p.productID }}"><img src="{{ STATIC_URL }}{{ p.image.url }}" alt="" /></a>
															<h2>₹ {{ p.price }}</h2>
															<p>{{ p.name }}</p>
															<form method = "POST" action = "/user/item_cart/">
															{% csrf_token %}
															<input type = "hidden" name = "addcart" value = {{ p.productID }}>
															<button type = "submit" class="btn btn-default add-to-cart"><i class="fa fa-shopping-cart"></i>Add to cart</button>
															</form>
														</div>
													</div>
												</div>
											</div>
											{% if forloop.counter|divisibleby:3 or forloop.last%}
											</div>
											{%endif%}
											{% endfor %}
									</div>
									
								</div>	
								<a class="left recommended-item-control" href="#recommended-item-carousel" data-slide="prev">
										<i class="fa fa-angle-left"></i>
									</a>
									<a class="right recommended-item-control" href="#recommended-item-carousel" data-slide="next">
										<i class="fa fa-angle-right"></i>
									</a>	
								
							<!--/recommended_items-->
			</div>
		</div>
					
	</div>
	</section><!--/slider-->
{%endblock%}

templates/login.html
<!DOCTYPE html>
{%extends 'base.html'%}

{% block title%}Shop{%endblock%}

{% block stylesheets%}
<link href = "{{STATIC_URL}}css/price-range.css" rel = "stylesheet">
<link href = "{{STATIC_URL}}css/jquery.simplecolorpicker.css" rel = "stylesheet">
<link href = "{{STATIC_URL}}css/jquery.simplecolorpicker-regularfont.css" rel = "stylesheet">
{%endblock%}

{% block ShopTogether %}
	<a href="#" onclick="TogetherJS(this); return false;" class="btn btn-default btn-lg" >Shop Together</a>
{% endblock %}

{% block body%}
	<section id="form"><!--form-->
		<div class="container">
			<div class="row" style="">
				<div class="col-sm-4 col-sm-offset-2">
					<div class="login-form" id = "wrapper"><!--login form-->
						<h2><b>Login to your account</b></h2>
						{{ state }}
						<form action="/user/login/" method = "POST">
						{% csrf_token %}
							{% if next %}
							<input type="hidden" name="next" value="{{ next }}" />
							{% endif %}
							<input type="text" name = "username" placeholder="username" required />
							<input type="password" name = "password" placeholder="Password" required/>
							<!-- <span>
								<input type="checkbox" class="checkbox"> 
								Keep me signed in
							</span> -->
							<button type="submit" class="btn btn-default">Login</button>
						</form>
					</div><!--/login form-->
				</div>
				<div class="col-sm-1">
					<h2 class="or">OR</h2>
				</div>
				<div class="col-sm-4">
					<div class="signup-form"  id = "wrapper"><!--sign up form-->
						<h2><b>New User Signup!</b></h2>
						{{ state2       }}
						<form action="/user/register/"  method = "POST" autocomplete="off">
						{% csrf_token %}
							<input type="text" name = "username" placeholder="username" required/>
							<input type="email" name = "email" placeholder="eg. john@gmail.com" pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,3}$" title="Please enter a valid email of the format john@gmail.com" required/>
							<input type="password" name = "password" placeholder="Password" required/>
							<button type="submit" class="btn btn-default">Signup</button>
						</form>
					</div><!--/sign up form-->
				</div>
			</div>
		</div>
	</section><!--/form-->
	
	{%endblock%}

templates/showproducts.html
{% load staticfiles %}
{% for p in products %}
						<div class="col-sm-4">
							<div class="product-image-wrapper">
								<div class="single-products">
									<div class="productinfo text-center">

										<img src="{{ STATIC_URL }}{{ p.image.url }}" alt="" width = "207" height = "250"/></a>
										<h2>{{ p.price }} rs.</h2>
										<p>{{ p.name }}</p>
										<p>{{ p.image.url }}</p>
									</div>

								</div>
								{% for i in p.images_set.all %}
									<h2>{{ i.name }}</h2>
									<p>{{ i.image.url }}</p>
									<img src ="{{STATIC_URL}}{{ i.image.url }}" width = "207" height = "250">
								{% endfor %}
							</div>
						</div>
						{% endfor %}